code-refactoring: Gitops 3127 implement applicationset controller package (#1011)
*add appset-controller 

---------

Signed-off-by: Yi Cai <yicai@redhat.com>

diff --git a/tests/controller/notifications/1-003_validate_notifications/05-verify-email.yaml b/tests/controller/notifications/1-003_validate_notifications/05-verify-email.yaml
--- a/tests/controller/notifications/1-003_validate_notifications/05-verify-email.yaml
+++ b/tests/controller/notifications/1-003_validate_notifications/05-verify-email.yaml
@@ -2,16 +2,16 @@ apiVersion: kuttl.dev/v1beta1
 kind: TestStep
 commands:
 - script: | 
-    set -e
-    smtp4dev_pod=$(kubectl get pod -l=app=smtp4dev -o NAME -n $NAMESPACE)
-    exit_code=$(kubectl -n $NAMESPACE exec -i --stdin "${smtp4dev_pod}" -- /bin/bash \
-    -c 'if [[ $(grep -rnw /tmp -e "Subject: Application my-app-3 has been created.") ]]; then
-    exit 0; else
-    exit 1;
-    fi')
+    pods=$(kubectl get pods -n $NAMESPACE -o NAME | grep "applicationset-controller")
 
-    if [ $exit_code=0 ]; then
-        exit 0
-    else
-        exit 1
-    fi
+    for pod in $pods; do
+        ready_status=$(kubectl get pod $pod -n $NAMESPACE -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}')
+
+        if [[ $ready_status == "False" ]]; then
+            echo "Pod $pod is not in Ready state as image is invalid."
+            exit 0
+        fi
+    done
+
+    echo "Unexpected: All pods are in Ready state."
+    exit 1
