feat: add e2e tests for operator
Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>

diff --git a/tests/k8s/1-006_validate-managed-by-chain/10-check-secret.yaml b/tests/k8s/1-006_validate-managed-by-chain/10-check-secret.yaml
--- a/tests/k8s/1-006_validate-managed-by-chain/10-check-secret.yaml
+++ b/tests/k8s/1-006_validate-managed-by-chain/10-check-secret.yaml
@@ -4,9 +4,15 @@ apiVersion: kuttl.dev/v1beta1
 kind: TestStep
 commands:
 - script: |
+    should="$NAMESPACE,test-1-12-custom2"
     namespaces=$(kubectl get secret -n $NAMESPACE argocd-default-cluster-config -o jsonpath='{.data.namespaces}' | base64 -d)
-    if test "$namespaces" != "$NAMESPACE"; then
-      echo "Assertion for cluster secret failed!"
-      exit 1
+    if test "$namespaces" != "$should"; then
+      echo "Assertion for cluster secret failed! '$namespaces' != '$should'"
+      # 1.2.0 doesn't reconcile the cluster secret on namespace deletion
+      if test GITOPS_TARGET_VERSION = "1.2.0"; then
+        exit 0
+      else
+        exit 1
+      fi
     fi
     exit 0
