fix the setting of environment variable ARGOCD_CONTROLLER_REPLICAS for dynamicScaling
Signed-off-by: Ishita Sequeira <ishiseq29@gmail.com>

diff --git a/tests/k8s/1-032_validate_dynamic_scaling/01-assert.yaml b/tests/k8s/1-032_validate_dynamic_scaling/01-assert.yaml
--- a/tests/k8s/1-032_validate_dynamic_scaling/01-assert.yaml
+++ b/tests/k8s/1-032_validate_dynamic_scaling/01-assert.yaml
@@ -4,3 +4,23 @@ metadata:
   name: argocd
 status:
   phase: Available
+---
+apiVersion: kuttl.dev/v1beta1
+kind: TestAssert
+timeout: 720
+commands:
+- script: |
+    stsReplicas=$(kubectl get sts argocd-application-controller -n $NAMESPACE -o jsonpath='{.status.replicas}')
+    echo "$stsReplicas"
+    if test "$stsReplicas" != "1"; then
+      echo "FAILED! Number of replicas not equal to desired replicas"
+      exit 1
+    fi
+    
+    replicaEnvVariable=$(kubectl exec -it -n $NAMESPACE argocd-application-controller-0 -- printenv | grep -i ARGOCD_CONTROLLER_REPLICAS)
+    echo "$replicaEnvVariable"
+    if test "$replicaEnvVariable" != "ARGOCD_CONTROLLER_REPLICAS=1"; then
+      echo "FAILED! ARGOCD_CONTROLLER_REPLICAS not equal to desired replicas"
+      exit 1
+    fi
+    exit 0
diff --git a/tests/k8s/1-032_validate_dynamic_scaling/02-assert.yaml b/tests/k8s/1-032_validate_dynamic_scaling/02-assert.yaml
--- a/tests/k8s/1-032_validate_dynamic_scaling/02-assert.yaml
+++ b/tests/k8s/1-032_validate_dynamic_scaling/02-assert.yaml
@@ -1,6 +1,3 @@
-apiVersion: kuttl.dev/v1beta1
-kind: TestAssert
-timeout: 720
 ---
 apiVersion: argoproj.io/v1alpha1
 kind: ArgoCD
@@ -15,3 +12,24 @@ metadata:
   name: argocd-application-controller
 status:
   replicas: 3
+---
+apiVersion: kuttl.dev/v1beta1
+kind: TestAssert
+timeout: 720
+commands:
+- script: |
+    stsReplicas=$(kubectl get sts argocd-application-controller -n $NAMESPACE -o jsonpath='{.status.replicas}')
+    echo "$stsReplicas"
+    if test "$stsReplicas" != "3"; then
+      echo "FAILED! Number of replicas not equal to desired replicas"
+      exit 1
+    fi
+    
+    replicaEnvVariable=$(kubectl exec -it -n $NAMESPACE argocd-application-controller-0 -- printenv | grep -i ARGOCD_CONTROLLER_REPLICAS)
+    echo "$replicaEnvVariable"
+    if test "$replicaEnvVariable" != "ARGOCD_CONTROLLER_REPLICAS=3"; then
+      echo "FAILED! ARGOCD_CONTROLLER_REPLICAS not equal to desired replicas"
+      exit 1
+    fi
+    exit 0
+
diff --git a/tests/k8s/1-032_validate_dynamic_scaling/03-assert.yaml b/tests/k8s/1-032_validate_dynamic_scaling/03-assert.yaml
--- a/tests/k8s/1-032_validate_dynamic_scaling/03-assert.yaml
+++ b/tests/k8s/1-032_validate_dynamic_scaling/03-assert.yaml
@@ -24,4 +24,11 @@ commands:
       echo "FAILED! Number of replicas not equal to maxShards"
       exit 1
     fi
+    
+    replicaEnvVariable=$(kubectl exec -it -n $NAMESPACE argocd-application-controller-0 -- printenv | grep -i ARGOCD_CONTROLLER_REPLICAS)
+    echo "$replicaEnvVariable"
+    if test "$replicaEnvVariable" != "ARGOCD_CONTROLLER_REPLICAS=4"; then
+      echo "FAILED! ARGOCD_CONTROLLER_REPLICAS not equal to maxShards"
+      exit 1
+    fi
     exit 0
