fix lint issues
Signed-off-by: Ishita Sequeira <ishiseq29@gmail.com>

diff --git a/tests/k8s/1-032_validate_dynamic_scaling/03-assert.yaml b/tests/k8s/1-032_validate_dynamic_scaling/03-assert.yaml
--- a/tests/k8s/1-032_validate_dynamic_scaling/03-assert.yaml
+++ b/tests/k8s/1-032_validate_dynamic_scaling/03-assert.yaml
@@ -17,18 +17,18 @@ apiVersion: kuttl.dev/v1beta1
 kind: TestAssert
 timeout: 720
 commands:
-- script: |
-    stsReplicas=$(kubectl get sts argocd-application-controller -n $NAMESPACE -o jsonpath='{.status.replicas}')
-    echo "$stsReplicas"
-    if test "$stsReplicas" != "4"; then
-      echo "FAILED! Number of replicas not equal to maxShards"
-      exit 1
-    fi
-    
-    replicaEnvVariable=$(kubectl exec -it -n $NAMESPACE argocd-application-controller-0 -- printenv | grep -i ARGOCD_CONTROLLER_REPLICAS)
-    echo "$replicaEnvVariable"
-    if test "$replicaEnvVariable" != "ARGOCD_CONTROLLER_REPLICAS=4"; then
-      echo "FAILED! ARGOCD_CONTROLLER_REPLICAS not equal to maxShards"
-      exit 1
-    fi
-    exit 0
+  - script: |
+      stsReplicas=$(kubectl get sts argocd-application-controller -n $NAMESPACE -o jsonpath='{.status.replicas}')
+      echo "$stsReplicas"
+      if test "$stsReplicas" != "4"; then
+        echo "FAILED! Number of replicas not equal to maxShards"
+        exit 1
+      fi
+
+      replicaEnvVariable=$(kubectl exec -it -n $NAMESPACE argocd-application-controller-0 -- printenv | grep -i ARGOCD_CONTROLLER_REPLICAS)
+      echo "$replicaEnvVariable"
+      if test "$replicaEnvVariable" != "ARGOCD_CONTROLLER_REPLICAS=4"; then
+        echo "FAILED! ARGOCD_CONTROLLER_REPLICAS not equal to maxShards"
+        exit 1
+      fi
+      exit 0
