Add test step to see clustersPerShard is ignored
Signed-off-by: ishitasequeira <ishiseq29@gmail.com>

diff --git a/tests/k8s/1-032_validate_dynamic_scaling/03-assert.yaml b/tests/k8s/1-032_validate_dynamic_scaling/03-assert.yaml
--- a/tests/k8s/1-032_validate_dynamic_scaling/03-assert.yaml
+++ b/tests/k8s/1-032_validate_dynamic_scaling/03-assert.yaml
@@ -1,3 +1,4 @@
+---
 apiVersion: argoproj.io/v1alpha1
 kind: ArgoCD
 metadata:
@@ -5,12 +6,22 @@ metadata:
 status:
   phase: Available
 ---
-apiVersion: v1
-kind: Pod
+apiVersion: apps/v1
+kind: StatefulSet
 metadata:
-  name: argocd-application-controller-0
+  name: argocd-application-controller
+status:
+  replicas: 4
 ---
-apiVersion: v1
-kind: Pod
-metadata:
-  name: argocd-application-controller-1
+apiVersion: kuttl.dev/v1beta1
+kind: TestAssert
+timeout: 720
+commands:
+- script: |
+    stsReplicas=$(kubectl get sts argocd-application-controller -n $NAMESPACE -o jsonpath='{.status.replicas}')
+    echo "$stsReplicas"
+    if test "$stsReplicas" != "4"; then
+      echo "FAILED! Number of replicas not equal to maxShards"
+      exit 1
+    fi
+    exit 0
